# Generated by Django 3.1.4 on 2020-12-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tilte', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('on_date', models.DateField()),
            ],
        ),
    ]
