# Generated by Django 3.1.4 on 2020-12-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itmgmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='attachement',
            field=models.FileField(blank=True, null=True, upload_to='data'),
        ),
    ]
