# Generated by Django 3.1.4 on 2020-12-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itmgmt', '0004_department_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
