# Generated by Django 3.1.4 on 2020-12-21 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itmgmt', '0005_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(max_length=200)),
                ('Line_1', models.CharField(max_length=200)),
                ('Line_2', models.CharField(max_length=200)),
                ('Line_3', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('pincode', models.CharField(max_length=200)),
                ('type_of', models.CharField(max_length=200)),
                ('address_type_of', models.CharField(max_length=200)),
                ('docstatus', models.CharField(max_length=3)),
                ('disable', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('pincode', models.CharField(max_length=20)),
                ('gstin', models.CharField(max_length=20)),
                ('docstatus', models.CharField(max_length=3)),
                ('disable', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=500)),
                ('type_of_details', models.CharField(max_length=200)),
                ('aadhaar', models.CharField(max_length=200)),
                ('voter_id', models.CharField(max_length=200)),
                ('driving_licence', models.CharField(max_length=200)),
                ('pan', models.CharField(max_length=200)),
                ('type_of', models.CharField(max_length=200)),
                ('docstatus', models.CharField(max_length=3)),
                ('disable', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Costcenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('pincode', models.CharField(max_length=20)),
                ('gstin', models.CharField(max_length=20)),
                ('docstatus', models.CharField(max_length=3)),
                ('disable', models.CharField(max_length=1)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itmgmt.company')),
            ],
        ),
        migrations.CreateModel(
            name='GST_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Item_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tax_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_group', models.CharField(max_length=1)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('pincode', models.CharField(max_length=20)),
                ('docstatus', models.CharField(max_length=3)),
                ('disable', models.CharField(max_length=1)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itmgmt.company')),
                ('costcenter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itmgmt.costcenter')),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rate', models.CharField(max_length=200)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itmgmt.company')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itmgmt.costcenter')),
                ('tax_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itmgmt.tax_type')),
            ],
        ),
        migrations.CreateModel(
            name='Manage_Device_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_info', models.CharField(max_length=200)),
                ('location_details', models.CharField(max_length=200)),
                ('mac_address', models.CharField(max_length=200)),
                ('cpu_desc', models.CharField(max_length=200)),
                ('motherboard_desc', models.CharField(max_length=200)),
                ('hdd_desc', models.CharField(max_length=200)),
                ('ram_desc', models.CharField(max_length=200)),
                ('monitor_desc', models.CharField(max_length=200)),
                ('other_desc', models.TextField()),
                ('username', models.CharField(max_length=200)),
                ('purpose', models.CharField(max_length=200)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itmgmt.department')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200)),
                ('UOM', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('serial_no', models.CharField(max_length=200)),
                ('batch_no', models.CharField(max_length=200)),
                ('barcode', models.CharField(max_length=200)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itmgmt.brand')),
                ('item_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itmgmt.item_type')),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=10)),
                ('type_of', models.CharField(max_length=200)),
                ('pan', models.CharField(max_length=40)),
                ('GSTIN', models.CharField(max_length=50)),
                ('commission_rate', models.CharField(max_length=50)),
                ('docstatus', models.CharField(max_length=3)),
                ('disable', models.CharField(max_length=1)),
                ('GST_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itmgmt.gst_category')),
                ('relation_ship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itmgmt.relationship')),
            ],
        ),
    ]
