# Generated by Django 3.1.4 on 2020-12-23 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itmgmt', '0006_auto_20201221_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=500)),
                ('account_number', models.CharField(max_length=200)),
                ('rate', models.CharField(max_length=200)),
                ('docstatus', models.CharField(max_length=1, null=True)),
                ('disable', models.CharField(max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Account_nature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Account_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Balance_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Discount_on',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Discount_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Equity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Frozen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Is_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item_rate_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Liability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Root_account_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Root_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='HSN_SAC',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='disable',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='docstatus',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='is_fixed_asset',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='is_purchase',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='is_salable',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='is_stock',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itmgmt.tax'),
        ),
        migrations.AlterField(
            model_name='address',
            name='disable',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='docstatus',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='docstatus',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='disable',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='docstatus',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='disable',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='docstatus',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='customer_supplier',
            name='disable',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='customer_supplier',
            name='docstatus',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='disable',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='docstatus',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.CreateModel(
            name='Parent_account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itmgmt.account')),
            ],
        ),
        migrations.CreateModel(
            name='Item_valuation_rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(max_length=200)),
                ('docstatus', models.CharField(max_length=1, null=True)),
                ('disable', models.CharField(max_length=1, null=True)),
                ('code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itmgmt.item')),
                ('item_rate_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itmgmt.item_rate_type')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itmgmt.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='Item_discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('discount_rate', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('qty', models.CharField(max_length=200)),
                ('docstatus', models.CharField(max_length=1, null=True)),
                ('disable', models.CharField(max_length=1, null=True)),
                ('discount_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itmgmt.discount_on')),
                ('discount_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itmgmt.discount_type')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='account_nature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itmgmt.account_nature'),
        ),
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itmgmt.account_type'),
        ),
        migrations.AddField(
            model_name='account',
            name='balance_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itmgmt.balance_type'),
        ),
        migrations.AddField(
            model_name='account',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itmgmt.company'),
        ),
        migrations.AddField(
            model_name='account',
            name='costcenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itmgmt.costcenter'),
        ),
        migrations.AddField(
            model_name='account',
            name='frozen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itmgmt.frozen'),
        ),
        migrations.AddField(
            model_name='account',
            name='is_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itmgmt.is_group'),
        ),
        migrations.AddField(
            model_name='account',
            name='root_account_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itmgmt.root_account_type'),
        ),
        migrations.AddField(
            model_name='account',
            name='root_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itmgmt.root_type'),
        ),
    ]
