# Generated by Django 3.1.4 on 2020-12-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itmgmt', '0007_auto_20201223_1127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Department'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User Details'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='tilte',
            new_name='title',
        ),
        migrations.AddField(
            model_name='account',
            name='entry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='entry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='entry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='entry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='entry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer_supplier',
            name='entry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='entry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item_discount',
            name='entry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item_valuation_rate',
            name='entry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='disable',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='entry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
