# Generated by Django 3.1.4 on 2020-12-24 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itmgmt', '0009_auto_20201223_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warranty_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='end_warrenty',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='item',
            name='model_no',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='start_warranty',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('duration', models.IntegerField()),
                ('docstatus', models.BooleanField(default=False)),
                ('disable', models.BooleanField(default=False)),
                ('warrenty_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itmgmt.warranty_type')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='warranty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itmgmt.warranty'),
        ),
    ]
