# Generated by Django 3.1.4 on 2020-12-24 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itmgmt', '0011_auto_20201224_0544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='end_warrenty',
        ),
        migrations.RemoveField(
            model_name='item',
            name='start_warranty',
        ),
    ]
