# Generated by Django 3.1.4 on 2020-12-24 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itmgmt', '0012_auto_20201224_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='end_warrenty',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='start_warranty',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
