# Generated by Django 3.1.4 on 2020-12-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itmgmt', '0014_auto_20201224_0610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('timestamp_lastupdated', models.DateTimeField(auto_now=True)),
                ('docstatus', models.BooleanField(default=True)),
                ('disable', models.BooleanField(default=False)),
            ],
        ),
    ]
