# Generated by Django 3.1.4 on 2020-12-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itmgmt', '0016_auto_20201225_0756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docstatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='is_group',
            field=models.BooleanField(default=True),
        ),
    ]
